global:
  scrape_interval: 15s # Tiempo entre capturas

scrape_configs:
  - job_name: 'spring-boot-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-service:8080'] 
      # Usamos 'host.docker.internal' para que el contenedor de Prometheus 
      # pueda ver tu API corriendo en tu Windows/Mac local.